name: if_else_statement
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  shared_preferences: ^2.2.2
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  device_preview: ^1.2.0

flutter:

  uses-material-design: true

  assets:
    - asset/
